Remove the SpoolTransport transport
getsentry/sentry-php pull request #1080
Opened 2020-09-02 10:01 UTC by ste93cry

The `SpoolTransport` was introduced as an attempt to have a transport that was able to persist events to a storage rather than sending them straight away. I now think that the implementation is not really useful, so I decided to cleanup all the codebase and stop offering it out of the box. If someone wants to delay sending of the events for some reason it's better to implement the feature directly in the project

2020-09-02 12:12 UTC, stayallive approved these changes
👍 good plan!

2020-09-02 13:40 UTC, Jean85 requested changes
I'm not sure about this... Wouldn't the `MemorySpool` still be useful for sending events at the end of the request?

2020-09-02 13:45 UTC, ste93cry commented
> Wouldn't the `MemorySpool` still be useful for sending events at the end of the request

Yes it could, but we don't have anymore a transport (at least implemented in the `3.x` branch) that is able to send events at the end of the request so keeping this code does not really makes sense. Also, we can always store the delayed events into the transport itself rather than relying on external storage

2020-09-03 06:02 UTC, Jean85 approved these changes

2020-09-03 08:41 UTC, merged