Update some deps and require at least PHP 7.2
getsentry/sentry-php pull request #1088
Opened 2020-09-13 20:57 UTC by ste93cry

Not much to say, minimum supported PHP version for `3.x` will be `7.2`. I also decided to update the required version of the `symfony/options-resolver` paclkage so that we are able to use the standard `value[]` syntax to validate that an option of type `array` contains only values of that type rather than writing our own validator function

2020-09-14 07:08 UTC, stayallive approved these changes
Seems reasonable, good 👍

2020-09-14 07:41 UTC, Jean85 approved these changes
Acceptable :+1: It should be noted that we dropped support only for very old Symfony versions.

2020-09-14 07:42 UTC, Jean85 requested changes
Wops! Changelog entry missing!

2020-09-16 08:03 UTC, Jean85 approved these changes

2020-09-16 08:07 UTC, merged