Make the environment always required
getsentry/sentry-php pull request #1116
Opened 2020-10-14 13:24 UTC by ste93cry

According to https://github.com/getsentry/develop/pull/169 the `environment` field is now always required. Since we have to maintain the compatibility we cannot just make the property `non-nullable`, so I added our very first deprecation of the `3.x` series that will suggest users to always pass a `string`. I also changed the default of the option as per documentation

2020-10-14 13:36 UTC, stayallive approved these changes
👍

2020-10-14 21:33 UTC, stayallive requested changes
Soooo actually there is some discussion about the actual value maybe needing to be `production` instead of `default`, see discussion in [#php on discord](https://discord.gg/TjCmyGC). Let's hold of a little bit before merging.

2020-10-14 21:43 UTC, stayallive requested changes
So that way quick: https://github.com/getsentry/develop/commit/676ab2bc2818d91ba8aa78dbf45768121f835420

We should change it to use `production` not `default` by default and allow the user to pass `null` if they want to (https://discordapp.com/channels/621778831602221064/621964286952210432/766052439660560384).

I guess that postpones our first deprecation for a bit 😉

2021-02-22 10:08 UTC, Jean85 requested changes

2021-02-22 10:08 UTC, Jean85 commented on src/Serializer/PayloadSerializer.php
> -        if (null !== $event->getEnvironment()) {
Can we revert this so we reduce the diff?

2021-02-22 16:03 UTC, stayallive approved these changes

2021-02-22 19:59 UTC, merged