Send stacktrace with events, not just exceptions
getsentry/sentry-php pull request #1123
Opened 2020-11-01 05:36 UTC by mfb

I noticed that if I set a stacktrace on an event, it is not sent to Sentry.  This patch should resolve the issue.

2020-11-01 10:54 UTC, ste93cry requested changes
Good catch! Can you please add a CHANGELOG entry and also a test case for this?

2020-11-01 10:54 UTC, ste93cry commented on src/Serializer/PayloadSerializer.php
> +        if ($stacktrace = $event->getStacktrace()) {
Can you please avoid assigning the variable in the `if` statement and check for `null` explicitly?

2020-11-02 07:29 UTC, Jean85 approved these changes

2020-11-02 09:11 UTC, ste93cry commented
I pushed a commit to the `master` branch to solve the broken CI, can you please rebase and try again if it works?

2020-11-02 11:02 UTC, ste93cry approved these changes

2020-11-02 11:07 UTC, merged

2020-11-09 01:08 UTC, mkopinsky commented
We've found (on an old version of the SDK - ^1.10) that for fatal errors/OOMs, sentry only gets the error but not the stack trace. Does this PR fix that? (Has it already been fixed since ^1.10?)

2020-11-09 08:22 UTC, Jean85 commented
This is on a completely different version (3.0), the issue is completely unrelated.