Add option to ignore errors from a specific tag
getsentry/sentry-php pull request #1201
Opened 2021-03-17 10:44 UTC by VincentLanglet

2021-03-17 11:40 UTC, ste93cry requested changes
Changes look good. Can you please also add a CHANGELOG entry?

**EDIT**
This feature should target the `develop` branch, can you please make the switch and rebase accordingly?

2021-03-17 11:40 UTC, ste93cry commented on tests/Integration/IgnoreErrorsIntegrationTest.php
> +        $event->setExceptions([new ExceptionDataBag(new \RuntimeException())]);
This should be useless for testing purposes

2021-03-17 11:40 UTC, ste93cry commented on tests/Integration/IgnoreErrorsIntegrationTest.php
> +        $event->setExceptions([new ExceptionDataBag(new \RuntimeException())]);
This should be useless for testing purposes

2021-03-17 12:31 UTC, VincentLanglet commented
Done @ste93cry :)

2021-03-17 23:31 UTC, VincentLanglet commented on CHANGELOG.md
> +- Add option `ignore_tags` to `IgnoreErrorsIntegration` in order to ignore exceptions by tags values.
Done

2021-03-18 08:12 UTC, Jean85 approved these changes

2021-03-18 08:48 UTC, ste93cry approved these changes
Thank you for the contribution 🎉

2021-03-18 08:48 UTC, merged

2021-03-26 12:20 UTC, VincentLanglet commented
@ste93cry You're welcome.

What is the release strategy of this package ? :) 
Just to have an idea about how much time I'll have to wait for this feature

2021-03-26 17:07 UTC, ste93cry commented
We have no real strategy, we accumulate some things and when we think we have enough features for a new minor version we release it. Sadly, I don't have any ETA for when this may happen though

2021-05-22 21:17 UTC, VincentLanglet commented
It's been two month, a new minor release would be really appreciate if it is possible :)

2021-05-26 09:32 UTC, ste93cry commented
Release [`3.3.0`](https://github.com/getsentry/sentry-php/releases/tag/3.3.0) is out :ship: