Swap order of Retry and Error http client plugins
getsentry/sentry-php pull request #1281
Opened 2022-01-17 08:58 UTC by blackwolf12333

The ErrorPlugin is responsible for filtering out requests that returned http
error codes. In the original order this filtering would happen only after a
failing request to the sentry endpoint was retried some number of times, as
configured by `getSendAttempts`.

This meant that when sentry rate limits the requests from this client the
requests would be retried before resulting in a ClientErrorException.

This patch reorders the ErrorPlugin and the RetryPlugin so the
ClientErrorException is thrown before the sdk attempts to retry the request.

Fixes #1204

2022-01-18 14:59 UTC, Jean85 requested changes
Please add a test (if possible) and a changelog entry.

2022-01-18 17:30 UTC, ste93cry commented
As mentioned in the issue, this is not the right solution: the order of the plugins matter, so swapping them will make `php-http/client-common:<2.0` work as expected and will break the app of all people using newer versions. Instead, we should bump the minimum required version of the package to ensure that noone can use one not behaving as expected

2022-01-19 09:23 UTC, Jean85 commented
> As mentioned in the issue, this is not the right solution: the order of the plugins matter, so swapping them will make `php-http/client-common:<2.0` work as expected and will break the app of all people using newer versions. Instead, we should bump the minimum required version of the package to ensure that noone can use one not behaving as expected

That should be done targeting `develop` though.

2022-01-19 09:27 UTC, ste93cry commented
I'm not sure, the bump is to solve an issue and as such it falls under a patch version

2022-01-19 10:16 UTC, Jean85 commented
Yes but, if you have issues to fix on the previous patch, there's no way to fix them for people stuck on `http/client-common` 1.x

IMHO we could even do the reverse on the old minor, restricting to `http/client-common` `^1.x` and fixing it there as suggested here.

WDYT?

2022-01-19 10:46 UTC, blackwolf12333 commented
Yeah I agree with @Jean85 here, I made this before the discussion on the issue happened. I don't really expect this to break people who use `client-common >= 2` but I can't be sure. Anyway, I'll close this PR until we have a good solution.

2022-01-19 10:46 UTC, closed without merging