Remove memory addresses from anonymous class frames
getsentry/sentry-php pull request #1315
Opened 2022-05-12 23:28 UTC by toemat

Match the new `${addr}` syntax as well as the previous `0x{addr}` syntax when stripping out the memory address so that events can group correctly again.

For https://github.com/getsentry/sentry-php/issues/1314

2022-05-13 06:07 UTC, stayallive commented
Could you also add a test so we don't regress in the future?

2022-05-13 17:27 UTC, toemat commented
Added a new test and updated CHANGELOG, thank you for the guidance! 🙌

2022-05-14 06:50 UTC, stayallive approved these changes

2022-05-15 16:37 UTC, ste93cry requested changes
Just some small changes and nitpicks, but good work overall

2022-05-15 16:37 UTC, ste93cry commented on tests/StacktraceTest.php
> +        yield 'Backtrace with frame containing memory address $ format' => [
What about changing the description to something more meaningful, e.g. `Backtrace with frame containing memory address in PHP >=7.4.2 format`?

2022-05-15 16:37 UTC, ste93cry commented on tests/StacktraceTest.php
> +        yield 'Backtrace with frame containing memory address 0x format' => [
What about changing the description to something more meaningful, e.g. `Backtrace with frame containing memory address in PHP <7.4.2 format`?

2022-05-16 16:54 UTC, ste93cry commented
I just realized that you are targeting the wrong branch. Since this is a bugfix, it should be merged into `master`

2022-05-16 16:56 UTC, toemat commented
Thank you @ste93cry, I really appreciate the review and guidance. I addressed the comments (should I respond to them, or 'resolve' them?). I'll switch the target to `master`.

2022-05-16 17:00 UTC, ste93cry commented
>should I respond to them, or 'resolve' them?

I don't think there is a right answer. Usually, I mark them as done if there's nothing more to add, and I leave a comment otherwise.

>I addressed the comments

Thank you for your work! A release will follow soon 🚢

2022-05-16 17:00 UTC, merged