Ability to set or remove single tag in the Event
getsentry/sentry-php pull request #1324
Opened 2022-05-25 21:02 UTC by Furgas

For easier event processing instead of `getTags -> change -> setTags`. Do you want me to add tests for these methods?

2022-06-01 20:11 UTC, ste93cry commented
I have nothing cons, however IIRC there had been already some discussion about whether such method had to be exposed or not, and it was a decision that had to be made cross-SDK. @vladanpaunovic can you please chime in?

2022-06-03 08:40 UTC, vladanpaunovic approved these changes
Hey @Furgas, thanks for your contribution!

I did a small [check across SDKs](https://cs.github.com/?scope=org%3Agetsentry&scopeName=getsentry&q=remove_tag) and many of our other SDKs already have these properties so I would add it here.

There is a [similar issue on Python](https://github.com/getsentry/sentry-python/issues/1344) too where we will have to align this.

@ste93cry, code looks fine to me. Feel free to review it.

2022-06-03 09:22 UTC, ste93cry requested changes
There are a few things off missing: first, an update of the CHANGELOG. Second, we should add these methods to the `Scope` class as well (which is where they are mostly useful). Last, please target the `develop` branch

2022-06-03 09:22 UTC, ste93cry commented on tests/EventTest.php
> +        $this->assertEquals([$tagName => $tagValue], $event->getTags());
Please use `assertSame`

2022-06-03 10:39 UTC, Furgas commented
> Second, we should add these methods to the `Scope` class as well

These methods are already in the `Scope` class. It was my motivation to add them to `Event` too, so I can use them in integrations (via `Scope::addGlobalEventProcessor`).

2022-06-03 10:56 UTC, ste93cry commented
You're right, I didn't check that before commenting and taken for granted that they weren't present already

2022-06-03 15:18 UTC, ste93cry requested changes

2022-06-03 15:18 UTC, ste93cry commented on CHANGELOG.md
> +- Add `setTag` and `removeTag` public methods to `Event` for easier manipulation of tags
Can you please add the reference to this PR at the end of the line?

2022-06-03 15:30 UTC, merged