fix: Add back xsi:noNamespaceSchemaLocation
getsentry/sentry-php pull request #1341
Opened 2022-08-11 14:56 UTC by cleptric

2022-08-11 17:30 UTC, ste93cry requested changes
Please revert also the changes that removed the `<coverage>` section, otherwise PHPUnit will not generate the code coverage report and Codecov won't work. It's not really important that there is a warning about the failed validation of the config file, as it's expected due to us running two completely different versions of PHPUnit because we have to support old PHP versions. If you are really bothered by that warning, we could simply split the `phpunit.xml.dist` into two, one for each version of PHPUnit, but I don't think it's worth it

2022-08-11 17:30 UTC, ste93cry commented on phpunit.xml.dist
> +    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Nitpick: do you mind aligning back all the attributes to where they were before your changes?

2022-08-12 08:12 UTC, cleptric commented
I'm wondering if it's necessary to upload the code coverage on each matrix run. Wouldn't one upload during Linux/8.1 suffice?

2022-08-12 08:31 UTC, ste93cry commented
No, because some tests run only for some PHP versions or some OS, so each coverage file gets uploaded and Codecov makes the sum of all of them and generates the final report

2022-08-12 08:32 UTC, ste93cry approved these changes

2022-08-12 08:35 UTC, merged