meta: Check for github-actions updates
getsentry/sentry-php pull request #1389
Opened 2022-09-30 14:00 UTC by cleptric

Let @dependabot do the work, so we don't have to 😄

2022-10-02 20:12 UTC, YasinAshorian approved these changes

2022-10-03 06:57 UTC, stayallive approved these changes

2022-10-03 08:45 UTC, Jean85 requested changes
What's the behavior of this? Does it change the `composer.json`? What about the `.lock`? What does it updates everything? Or just against CVEs?

2022-10-03 08:57 UTC, stayallive commented
@Jean85 this does only `package-ecosystem: "github-actions"`.

Composer is not touched or looked at.

2022-10-03 10:01 UTC, Jean85 approved these changes

2022-10-03 14:14 UTC, merged